### ISSUE TITLE
[lnurl-pay] return `null` if there is no successAction

### ISSUE THREAD

**Issue by eillarra** [fiatjaf/go-lnurl#1]
Currently it returns `{"tag": "noop"}`, but that is not included in [the spec](https://github.com/btcontract/lnurl-rfc/blob/master/spec.md#4-lnurl-pay).

This line should be changed: https://github.com/fiatjaf/go-lnurl/blob/c7406f28054d0a1a31e10aab7bdb1d862d4bbeec/types.go#L38

**Comment by fiatjaf** [comment]
Fixed in ea4b69f.

Just removed that helper, because you can now just set `SuccessAction` to `nil` (and that is the default).

**Comment by eillarra** [comment]
If `sucessAction` is nil nothing is included in the response now; but the response should include `"successAction": null`.

**Comment by fiatjaf** [comment]
Sorry, fixed now on 8a6463e.
