### ISSUE TITLE
Description Hash check

### ISSUE THREAD

**Issue by PatrickGeyer** [fiatjaf/go-lnurl#19]
I thought lnurl is not meant to check description hash of invoice anymore? 
<img width="638" alt="Screenshot 2023-09-13 at 13 04 44" src="https://github.com/fiatjaf/go-lnurl/assets/5664617/ef8199a1-fafa-4c71-b269-eaba3eadbdbb">

**Comment by PatrickGeyer** [comment]
https://github.com/lnurl/luds/pull/234

**Comment by fiatjaf** [comment]
Why are you so rude?
