### ISSUE TITLE
params.Metadata.Encode() doesn't add a space

### ISSUE THREAD

**Issue by cj-ibex** [fiatjaf/go-lnurl#6]
```
func (params LNURLPayParams) MetadataEncoded() string {
	if params.EncodedMetadata == "" {
		params.EncodedMetadata = params.Metadata.Encode()
	}
	return params.EncodedMetadata
}
```

In this code, `params.Metadata.Encode()` doesn't add a space when encoding the description. 

Current---> `"[[\"text/plain\",\"hello\"]]"`
Expected-> `"[[\"text/plain\", \"hello\"]]"`

I can get around this by setting the `EncodedMetadata` directly, but I believe the space should be included automatically?

**Comment by fiatjaf** [comment]
Why is a space expected?

**Comment by cj-ibex** [comment]
If I create a lnurlp on lnbits, the space is included in the description hash. Using the method above removed the space thus causes a mismatch in description hash.

I'm still playing around with this library so let me know if I'm misunderstanding something

**Comment by fiatjaf** [comment]
If you are reading the lnurlp from lnbits, then this library should populate `EncodedMetadata` with whatever it got from lnbits and you should use that to check the hash, never try to reencode anything, the `.Encode()` function is for when you are using this library to generate your own lnurlp/metadata.

(Let me know if it is not working like I described above -- writing software without tests has some risks.)

**Comment by cj-chua** [comment]
Ok that makes sense. Setting EncodedMetadata did it for me

**Comment by fiatjaf** [comment]
That's notquitewhat I said, but fine!

**Comment by fiatjaf** [comment]
Yes, except for the fact that `.EncodedMetadata` should be already filled with the metadata string as received from the service when you call `HandleLNURL()` or if you do `json.Unmarshal()` with `LNURLPayParams` and the received JSON response (that's what `HandleLNURL()` does).
