### ISSUE TITLE
Makes FindLNURLInText return original case

### ISSUE THREAD

**Issue by ademar111190** [fiatjaf/go-lnurl#9]
A bug was reported to Breez wallet regarding the case sensitivity of lnurl, context here https://github.com/breez/breezmobile/issues/949

Studying the problem I found the case of the URL is being changed here https://github.com/breez/breez/blob/master/account/lnurl.go#L40 more specifically here https://github.com/fiatjaf/go-lnurl/blob/master/helpers.go#L15

So I'm opening this issue because if FindLNURLInText returns the original case of the text argument we can solve this problem without any bad side effects on the working cases.

Let me know if I can help.

**Comment by fiatjaf** [comment]
This seems to be a problem only when parsing LNURLs in the format `lnurlw://...`, right? Not `lnurl1...`.

Fixed that in v1.11.2. Thank you very much!
